pipeline {
    agent any
    environment {
        APP_URI_MODEL = credentials('app-uri-model') // Nom du credential pour APP_URI
        APP_URI_API = credentials('app-uri-api') // Nom du credential pour APP_URI
        AWS_ACCESS_KEY_ID = credentials('aws-access-key-id') // Credential AWS Access Key
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key') // Credential AWS Secret Key
        BACKEND_STORE_URI_MODEL = credentials('backend-store-uri-model') // Credential Backend Store URI
        BACKEND_STORE_URI_API = credentials('backend-store-uri-api') // Credential Backend Store URI
        ARTIFACT_STORE_URI = credentials('artifact-store-uri') // Credential Artifact Store URI
        POSTMARK_API_KEY = credentials('postmark-api-key') // Credential Postmark API Key
        MLFLOW_EXPERIMENT_NAME = credentials('mlflow-experiment-name') // Nouvelle variable ajoutée
        MLFLOW_TRACKING_URI = credentials('mlflow-tracking-uri') // Nouvelle variable ajoutée
    
    }
    
    stages {
        stage('Checkout') {
            steps {
                // Cloner le code source depuis GitHub
                checkout scm
            }
        }

        stage('Build Docker Images') {
            steps {
                parallel (
                    "Build MLflow Image": {
                        dir('CICD/mlflow') {
                            sh 'docker build -t mlflow-image .'
                        }
                    },
                    "Build API Image": {
                        dir('CICD/API') {
                            sh 'docker build -t fraud-detection-api .'
                        }
                    }
                )
            }
        }

        stage('Generate .env File') {
            steps {
                dir('CICD') {
                    script {
                        writeFile file: '.env', text: """
APP_URI_MODEL=${APP_URI_MODEL}
APP_URI_API=${APP_URI_API}
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
BACKEND_STORE_URI_MODEL=${BACKEND_STORE_URI_MODEL}
BACKEND_STORE_URI_API=${BACKEND_STORE_URI_API}
ARTIFACT_STORE_URI=${ARTIFACT_STORE_URI}
POSTMARK_API_KEY=${POSTMARK_API_KEY}
MLFLOW_EXPERIMENT_NAME=${MLFLOW_EXPERIMENT_NAME}
MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}

"""
                    }
                    // Afficher le contenu pour vérification (supprimez cette ligne en production)
                    sh 'cat .env'
                }
            }
        }
