pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials('aws-access-key-id') // Credential AWS Access Key
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key') // Credential AWS Secret Key
        BACKEND_STORE_URI = credentials('backend-store-uri') // Credential Backend Store URI
        ARTIFACT_STORE_URI = credentials('artifact-store-uri') // Credential Artifact Store URI
        POSTMARK_API_KEY = credentials('postmark-api-key') // Credential Postmark API Key
       
    }
    stages {
        stage('Checkout') {
            steps {
                // Cloner le code source depuis GitHub
                checkout scm
            }
        }

        stage('Generate .env File') {
            steps {
                dir('CICD') {
                    script {
                        // Générer le fichier .env avec les variables d'environnement
                        writeFile file: '.env', text: """
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
BACKEND_STORE_URI=${BACKEND_STORE_URI}
ARTIFACT_STORE_URI=${ARTIFACT_STORE_URI}
POSTMARK_API_KEY=${POSTMARK_API_KEY}
"""
                    }
                    // Vérifier le contenu du fichier .env (supprimer cette ligne en production)
                    sh 'cat .env'
                }
            }
        }

        stage('Build Docker Images') {
            steps {
                dir('CICD/mlflow') {
                    sh 'docker build -t mlflow-image .'
                }
            }
        }

        stage('Run Training Script') {
            steps {
                dir('CICD/mlflow') {
                    script {
                        // Démarrer le conteneur pour exécuter le script train.py
                        sh """
                        docker run --rm --env-file ../.env \
                            -v "\$(pwd):/home/app" \
                            mlflow-image python /home/app/train.py
                        """
                    }
                }
            }
        }
    }
    post {
        always {
            // Nettoyer les conteneurs créés pendant le pipeline
            echo "Nettoyage des conteneurs Docker..."
            sh 'docker container prune -f || true'
        }
        success {
            echo 'Pipeline exécutée avec succès !'
        }
        failure {
            echo 'La pipeline a échoué.'
        }
    }
}
